Dockerfile, peregrine/resources/submission/graphql/node.py, requirements.txt
the master branch of peregrine use an old version of gdcdatamodel which doesn't respect dictionary pulled from s3
also fix the docker file to install peregrine so that the logs doesn't complain about can't find peregrine.api
=> fix(datamodel): use correct datamodel

peregrine/resources/submission/graphql/node.py
WithPathToInput type was defined before dictionary was loaded, so all attributes defined in dictioanry are not mapped to graphql
This creates the type when get_schema is called and cache it in function args
TODO:
need to fix the unit tests to load dictionary from s3 and have a clean environment without loading installed gdcdictionary and gdcdatamodel #23
=> fix(graphql): load types after dictionary

requirements.txt
the uc-cdis gdcdatamodel that works for dictionary that does not have `case`
=> feat(datamodel): use uc-cdis datamodel

Dockerfile, deployment/nginx/nginx.conf, deployment/nginx/uwsgi.conf
integrate nginx logging and nginx uwsgi config
with X-Forwarded-For and X-UserId headers
supplied by the reverse proxy, so peregrine logs
have the client ip and user id
resolve #24
=> fix(logging): log user id and real ip

peregrine/resources/submission/graphql/util.py
the name of projects the user doesn't have access to won't be displayed on the index page or the data submission page or when querying projects
=> PXD-1377 fix(unauthorized-projects)

.travis.yml, requirements.txt
- dictionaryutils 2.0.2 -> 2.0.4 to support nested subgroups
- gdcdatamodel 1.3.4 -> 1.3.6 to support nested subgroups
=> chore(dictutils): bump dictutils

dev-requirements.txt
- urllib3 1.22->1.23 for tests to address security vulnerability
=> (chore(urllib3): bump urllib3 for tests

peregrine/resources/submission/graphql/node.py
Fix for `first=0` for `datanode` and `_node_type`
- Fixes the argument `first` in `datanode` and `_node_type` interfaces so that `first=0` will return all the results
=> PXP-1421 Fix/first

peregrine/resources/submission/graphql/node.py
This gives the `Node` interface access to the `submitter_id` field. All the nodes have a `submitter_id`, except `program` and `project` nodes, so their `submitter_id` will be null.
This is needed for the data upload feature.
- Add the `submitter_id` field to the `Node` interface
=> fix(node-submitterid): add submitter_id to node interface

peregrine/api.py, peregrine/dev_settings.py, peregrine/resources/submission/graphql/traversal.py
fix(lazy-traverse)
* No tests found for traversal code, suggest a new ticket to cover them
* Also added config `USE_LAZY_TRAVERSE` to revert to old behavior
* May easily implement "after-start-up preload" based on this PR
* First few GraphQL queries with `with_path_to` filter may be slower.
* Now the traversal cache is no longer loaded at startup, so it should be faster to start
=> PXD-2355: lazy load traversal cache

.travis.yml, openapis/swagger.yaml, peregrine/api.py, peregrine/blueprints/datasets.py, peregrine/resources/submission/__init__.py, run_tests.sh, tests/conftest.py, tests/graphql/test_datasets.py
This implements the datasets endpoint that allows anonymous request(if configured) for tiered access feature.
ticket: https://ctds-planx.atlassian.net/browse/PXP-2463
deliverable: https://ctds-planx.atlassian.net/wiki/spaces/PLA/pages/29851651/Tiered+Access
cloud-automation pr: https://github.com/uc-cdis/cloud-automation/pull/699
- Add /datasets endpoint to return summary counts for project and allow it to be configured to be public endpoint
- a new environment variable PUBLIC_DATASETS will be required to set for anonymous access to datasets endpoint
=> feat(datasets): add datasets endpoint

peregrine/resources/submission/graphql/node.py, tests/graphql/test_graphql.py
Refs #100 
* Fixed bug that `datanode(object_id: "xxx")` returns empty list when xxx exists.
=> PXD-2482: fix datanode(object_id:"xx")->[]

peregrine/resources/submission/graphql/node.py
TODO: Write tests for:
* Fixed bug that `node(category, of_type)` returns dupilcate nodes
* Fixed bug that `datanode(of_type)` returns duplicate nodes
* Fixed bug that `first` is not working correctly for multiple categories, e.g. `node(category:"c1,c2", first:n)`
* Performance of `node(category, of_type)` and `datanode(of_type)` is improved.
=> fix(node): fix of_type bug

peregrine/blueprints/datasets.py, tests/conftest.py, tests/graphql/test_datasets.py
- make authenticated but not authorized requests to datasets endpoint return 200
=> chore(datasets): unauthorized call return 200

peregrine/resources/submission/graphql/node.py
Fixes a bug when a data node contains an array field (such as https://github.com/uc-cdis/ndhdictionary/blob/0c5f2a97a3fa470d31e6886b7483d036cd5e81a4/gdcdictionary/schemas/sequencing_result.yaml#L102)
```
lookup_graphql_type(types[0])()
TypeError: 'List' object is not callable
```
Also add a note for future; we should instantiate array fields by doing `graphene.List(actual type of the items)` but for now we assume the items are String.
- Fix bug when a data node contains an array field
=> fix(datanode-array)

peregrine/resources/submission/graphql/node.py, tests/graphql/test_graphql.py
* Now `quick_search: ""` is ignored for performance.
=> PXD-2479: empty quick_search values shouldn't apply

.travis.yml, dev-requirements.txt, peregrine/test_settings.py, tests/conftest.py, tests/utils.py
Remove pyasn1-modules, urllib3, cirrus, userdatamodel, and fence from dev-requirements.txt; just inline the code for token generation (= copy paste a bunch of code from fence/fence/jwt/token to peregrine/tests/utils, but at least fence is no longer a dependency)
Remove pyasn1-modules, urllib3, cirrus, userdatamodel, and fence from dev-requirements
=> [PXP-3221] Refactor/fence

dev-requirements.txt, peregrine/dev_settings.py, peregrine/test_settings.py, requirements.txt, run.py, tests/conftest.py
Remove signpost from peregrine dependencies and code
- stops importing and using signpost in testing, and stops calling index client signpost where index client is already being used instead of signpost
- point gen3datamodel to temporary branch until sqlalchemy and psqlgraph get updated
- bump indexclient to 1.5.7
- bump flaks-postgres-session to 0.1.4
- remove signpost from dev-requirements
- look for INDEX_CLIENT instead of SIGNPOST in app.config
- get INDEX_CLIENT_HOST env var instead of SIGNPOST_HOST
=> Remove signpost

Dockerfile, dev-requirements.txt, peregrine/api.py, requirements.txt
PyYAML:
Happily, Peregrine was already using PyYAML's `safe_load()` instead of `load()`. So we were good to just bump. 
gdcdictionary: 
Now that gdcdictionary is a PyPI package its location in the Docker container changed. So the `cd` in the RUN part of the Dockerfile broke. The `cd` along with the lines after it served to write version information about gdcdictionary to `version_data.py`. This PR changes the Peregrine `/_version` endpoint to just get the gdcdictionary version programmatically, so that we can remove the broken lines in the Dockerfile. The dictionary commit hash is removed entirely now that we are getting gdcdictionary via PyPI. 
flask:
import CORS from flask_cors not flask.ext.cors
change the Peregrine /_version endpoint to just get the gdcdictionary version …
=> bump sqlalchemy, pyyaml, bunch of other stuff

peregrine/auth/__init__.py, tests/conftest.py, tests/graphql/test_graphql.py
users who are not in the user.yaml can't query, they get the error: `Authentication Error: Unable to retrieve auth mapping: [500] - user does not exist: xxx`
Peregrine should return empty data instead
- Return empty data instead of an error when arborist does not recognize a user
=> fix(arborist): no error for unknown user

dev-requirements.txt, requirements.txt, tests/conftest.py
Bump flask to the latest version
also bump pytest to 4.6.5 (latest version that supports python 2) and pytest-flask to 0.15.0 (latest version) to fix unit test issues
- Flask 1.1.1, Werkzeug 0.16.0
=> Bump flask to 1.1.1

.secrets.baseline, peregrine/resources/submission/__init__.py
OPEN projects are double counted because they appear in both open read access privileges and authorized user level privileges. Bug fix makes sure peregrine is aware of this and does not add project_ids to list of projects if it is already in the list because it's an open project.
https://ctds-planx.atlassian.net/browse/PXP-2403
Fix bug where project id count returns 2 instead of 1
=> PXP-2403 fix duplicate project id bug

peregrine/api.py, peregrine/resources/submission/__init__.py, peregrine/resources/submission/graphql/__init__.py
Fix this error seen in IBD Prod Peregrine:
```
File "/peregrine/peregrine/resources/submission/graphql/__init__.py", line 126, in <listcomp>
errors = [err.message for err in result.errors]
AttributeError: 'Exception' object has no attribute 'message'
```
relates to https://github.com/uc-cdis/pidgin/pull/40
- Handle exceptions without 'message' attribute
=> Handle exceptions without 'message' attribute

peregrine/blueprints/datasets.py, tests/graphql/test_datasets.py
Bug: if `nodes == ""`, then `nodes.split(",") == [""]` and we don't run the `if not nodes` statement
- Fix `/datasets` to correctly return an error when no `nodes` parameter is provided
=> /datasets correctly return an error when no 'nodes' parameter.

bin/setup_psqlgraph.py, peregrine/resources/submission/graphql/node.py, tests/graphql/test_graphql.py
Link to JIRA ticket if there is one: 
- Fix a bug when querying datanode with `first` filter. The bug was mitigated by datanode queries now returning the first `<limit>` items for each file node.
=> Fix bug when querying datanode with 'first' filter
