.codacy.yml
.travis.yml
Dockerfile
README.md
dev-requirements.txt
openapis/README.md
openapis/swagger.yaml
peregrine/auth/__init__.py
peregrine/resources/submission/__init__.py
peregrine/resources/submission/graphql/counts.py
peregrine/resources/submission/graphql/node.py
peregrine/resources/submission/graphql/transaction.py
peregrine/resources/submission/graphql/util.py
requirements.txt
tests/conftest.py
tests/graphql/test_graphql.py

⚡️Upgrade to graphene 2.0.1
Pull in Justin’s test upgrades from gdcapi, 5 secs faster
Fix open access projects so they work correctly, resolves uc-cdis/gdcapi#85
Transaction log performance enhancement
Cleans up travis yml removing conda because we don't need it.
Adds swagger yaml

Bug fixes and performance improvements 

---

peregrine/resources/submission/__init__.py

same fix as in https://github.com/uc-cdis/gdcapi/pull/96/files

fix(avail): don't assume project has avail

---

deployment/uwsgi/uwsgi.ini

big cookie header thanks to jwt
http://uwsgi-docs.readthedocs.io/en/latest/Options.html#buffer-size

fix(buffer-size): uwsgi not happy with big headers

---

peregrine/dev_settings.py
peregrine/resources/submission/graphql/node.py

resolve #30 
@zflamig @philloooo

fix(kf_dictionary): fix kf dictionaty

---

deployment/nginx/nginx.conf

for https://github.com/uc-cdis/cloud-automation/issues/219

feat(security): bump max worker connections

---

peregrine/dev_settings.example.py

for use with local Docker Compose setup

chore(dev_settings_example): added FORCE_ISSUER option

---

deployment/nginx/uwsgi.conf

/getschema is taking more that 20 seconds in VADC

fix(uwsgi.conf): extend nginx/uwsgi timeout

---

.gitignore
peregrine/api.py
peregrine/resources/submission/__init__.py
peregrine/resources/submission/graphql/__init__.py

Feat/getschema - PXD-1259 dump schema to local file

---

peregrine/resources/submission/graphql/node.py
run.py

- check if a dictionary field is a list when converting json type to graphql type
- fixed import in run.py

PXD-1757 Fix/array type

---

requirements.txt

- requests 2.5.2 -> 2.20.0 for security patch

chore(dep): bump requests to 2.20.0 for security

---

dev-requirements.txt
peregrine/resources/submission/graphql/traversal.py
tests/conftest.py

This branch has some moderate speedup for app initialization, but there's more potential for improvement; going to continue on refactor/traversal
None
None
None
Change `construct_traversals_from_node` to be non-recursive & more efficient. Note that `make_graph_traversal_dict` is still not optimal because some traversals will overlap.
None
None

fix(traversal): impelement traversal non-recursively

---

Jenkinsfile.performance

adding Jenkinsfile.performance

---

peregrine/resources/submission/graphql/__init__.py
peregrine/resources/submission/graphql/node.py
requirements.txt

This mitigates the issue in PXD-2336.
* Now specific count queries are always grouped for one request, and generated in raw SQL

PXD-2336: fix(promise): use promise to group count queries

---

Jenkinsfile.performance

Update `cdis-jenkins-lib` branch.

feat(perf): cdis-jenkins-lib branch

---

peregrine/blueprints/datasets.py

- make datasets public config case insensitive

chore(datasets): make flag case insensitive

---

openapis/swagger.yaml
peregrine/blueprints/datasets.py
tests/graphql/test_datasets.py

- Implements /datasets/projects endpoint that has the same access control mechanism as /datasets

feat(projects): add projects endpoint

---

peregrine/blueprints/datasets.py

- fix datasets regex which only match single digit index

fix(datasets): match projects more than 10

---

deployment/uwsgi/uwsgi.ini

- remove global harakiri setting

chore(uwsgi-logs)

---

Dockerfile

chore(docker): use pybase-1.0.2

---

peregrine/api.py
requirements.txt

bump gen3dictionary

---

peregrine/api.py
peregrine/dev_settings.py
peregrine/test_settings.py

- ARBORIST_URL environment variable replaces broken default ARBORIST config variable

fix(arborist-url)

---

peregrine/resources/submission/graphql/node.py
tests/graphql/test_graphql.py

Closes https://github.com/uc-cdis/peregrine/pull/153
Reproduced the bug and manually tested this fix
- Fix creation date and update date filters

PXP-4760 Fix creation date and update date filters

---

bin/setup_psqlgraph.py
bin/setup_test_database.py
peregrine/api.py
peregrine/dev_settings.example.py
peregrine/dev_settings.py
peregrine/dictionary.py
peregrine/models.py
peregrine/resources/submission/__init__.py
peregrine/resources/submission/constants.py
peregrine/resources/submission/graphql/counts.py
peregrine/resources/submission/graphql/node.py
peregrine/resources/submission/graphql/transaction.py
peregrine/resources/submission/graphql/traversal.py
peregrine/test_settings.py
peregrine/utils/scheduling.py
run.py
tests/conftest.py
tests/graphql/conftest.py
tests/graphql/test_graphql.py
tests/graphql/test_transaction_logs.py

- Running Peregrine locally with mocked authz no longer requires passing access tokens

fix(mock-authz): running locally does not require auth header

---

.pre-commit-config.yaml
.secrets.baseline

This repo contains flask secret key in dev_settings.py and dev_settings_example.py
Otherwise there were some md5sum of file objects but that should be fine.

Pre-Commit Hooks

---

.travis.yml
requirements.txt

closes #164
- Fix dependency resolution issue: python-keystoneclient to ~=1.8, addict to ~=2.1

Fix dependency resolution issue

---

Dockerfile

- Adopt new base img with dd apm

chore(observability): Adopt new base img with dd apm

---

Dockerfile

Jira Ticket: [PXP-8935](https://ctds-planx.atlassian.net/browse/PXP-8935)
- Use new Python base image (now: Debian, before: Alpine)

PXP-8935 Use pybase3-2.0.0 base image

---

.github/labeler.yml
.github/workflows/labeler.yml

Jira Ticket: [GQE-74](https://ctds-planx.atlassian.net/browse/GQE-74)
[GQE-74]: https://ctds-planx.atlassian.net/browse/GQE-74?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

adding labeler to peregrine

---

.secrets.baseline
peregrine/api.py
peregrine/auth/__init__.py
peregrine/blueprints/coremetadata.py
tests/graphql/test_coremetadata.py

- Log more error details in the core metadata endpoint

Log more errors in core metadata endpoint

---

peregrine/resources/submission/graphql/__init__.py

Link to JIRA ticket if there is one: 
- add GraphQL query itself to existing log about GraphQL timing

chore(logging): add query to timing log
